### ISSUE TITLE
DOCS: Game contract documentation

### ISSUE THREAD

**Issue by alilloig** [onflow/sc-eng-gaming#13]
### Issue To Be Solved
Document the solution for the [Game contract proposal](https://github.com/onflow/sc-eng-gaming/issues/7)

### (Optional): Suggest A Solution
(Replace This Text: A concise description of your preferred solution. Things to address include:
* Details of the technical implementation
* Tradeoffs made in design decisions
* Caveats and considerations for the future

If there are multiple solutions, please present each one separately. Save comparisons for the very end.)
  
### (Optional): Context

<what are you currently working on that this is blocking?>

**Comment by joshuahannan** [comment]
@sisyphusSmiling is this complete or does it need more work?

**Comment by sisyphusSmiling** [comment]
I can get README updated next week. Changes are needed after the last hybrid custody refactor
