### ISSUE TITLE
Add support for returning a single NFT from a Match

### ISSUE THREAD

**Issue by alilloig** [onflow/sc-eng-gaming#30]
### Problem
If one of the two players of a match would create a custom `deposit()` for the `{NonFungibleToken.Receiver}` that panics somehow, that will stop the `returnNFT()` method from giving back the NFT to the honest player. We need to create a separate method for returning a single NFT from a match for allowing players to always get back their NFTs from matches

**Comment by sisyphusSmiling** [comment]
Closed by #39
